name: shot_select
description: "Shot Select is photo culling software"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_libraw: ^0.0.1
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  injectable: ^2.3.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  injectable_generator:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
